## Introduction to Natural Language Processing

### Install NLTK
```pip install nltk```

In [1]:
import nltk

In [2]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

## 1. Get the Data
- Get the Data from NLTK Corpora
- or Scrape the Data/ Use API

In [3]:
# Corpus - A large collection of text


from nltk.corpus import brown

In [4]:
print(brown.categories())
print(len(brown.categories()))

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']
15


In [12]:
data = brown.sents(categories='reviews')
len(data)

1751

In [15]:
#1 sentence in fiction category
' '.join(data[0][:-1])

'It is not news that Nathan Milstein is a wizard of the violin'

### Bag of Words Pipeline
- Get the Data/Corpus
- Tokenisation, Stopward Removal
- Stemming, Lemmatization
- Building a Vocab
- Vectorization
- Classification

### Tokenisation & Stopword Removal

In [22]:
document = """It was a very pleasant day. The weather was cool and there were light showers. 
I went to the market to buy some fruits."""

sentence = "Send all the 50 documents related to chapters 1,2,3 at shubham@cb.com"

In [23]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [24]:
sents = sent_tokenize(document)
print(sents)
print(len(sents))

['It was a very pleasant day.', 'The weather was cool and there were light showers.', 'I went to the market to buy some fruits.']
3


In [25]:
sents[0]

'It was a very pleasant day.'

In [26]:
sentence.split()

['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapters',
 '1,2,3',
 'at',
 'shubham@cb.com']

In [27]:
words = word_tokenize(sentence)
words

['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapters',
 '1,2,3',
 'at',
 'shubham',
 '@',
 'cb.com']

## Stopwords

In [80]:
from nltk.corpus import stopwords

sw = set(stopwords.words('english'))

In [81]:
print(sw)

{"you're", 'down', 'and', 'no', "she'd", "couldn't", 'which', 'myself', 'where', 'above', 'having', 'won', "they'd", "mightn't", 'm', 'are', "i'll", 'yours', 'an', 'for', 'because', 'itself', 'couldn', 'as', 'i', 'll', 'by', 'their', 'did', 'than', 'why', "should've", "didn't", 'been', 'haven', "wouldn't", 'nor', 'was', 'each', 'y', "she'll", "it's", 'herself', "hasn't", "don't", 'but', 'theirs', "we've", 'if', 'here', 'before', 'doing', 'after', 're', 'have', 'off', 'on', 'below', 'again', 'aren', 'those', 'with', "that'll", 'didn', 'over', 'mustn', 'once', "they'll", 'wasn', 'd', 's', 'shouldn', 'were', "i'm", 't', 'them', 'out', 'do', "you've", 'hasn', "i've", 'only', 'weren', 'this', 'himself', "we'd", "doesn't", 'through', 'she', 'my', "needn't", 'her', 'from', "you'll", 'more', 'any', 'being', "weren't", 'our', 'other', 'same', 'hadn', "he'd", "she's", 'can', 'needn', "wasn't", 'between', 'against', 'him', 'should', 've', 'ain', 'few', 'that', 'yourself', "hadn't", 'all', "it'll"

In [75]:
def remove_stopwords(text,stopwords):
    useful_words = [w for w in text if w not in stopwords]
    return useful_words

In [16]:
text = "i am not bothered about her very much".split()
useful_text = remove_stopwords(text,sw)
print(useful_text)

['bothered', 'much']


### Tokenization using Regular Expression

In [28]:
sentence = "Send all the 50 documents related to chapters 1,2,3 at shubham@cb.com"

In [29]:
from nltk.tokenize import RegexpTokenizer

In [30]:
tokenizer = RegexpTokenizer('[a-zA-Z@.]+')
useful_text = tokenizer.tokenize(sentence)

In [31]:
useful_text

['Send',
 'all',
 'the',
 'documents',
 'related',
 'to',
 'chapters',
 'at',
 'shubham@cb.com']

### Stemming
- Process that transforms particular words(verbs,plurals)into their radical form
- Preserve the semantics of the sentence without increasing the number of unique tokens
- Example - jumps, jumping, jumped, jump ==> jump

In [32]:

text= """Foxes love to make jumps.The quick brown fox was seen jumping over the 
        lovely dog from a 6ft feet high wall"""


In [33]:
from nltk.stem.snowball import SnowballStemmer, PorterStemmer
from nltk.stem.lancaster import LancasterStemmer
#Snowball Stemmer, Porter, Lancaster Stemmer

In [34]:
ps = PorterStemmer()

In [44]:
ps.stem('curled')

'curl'

In [36]:
ps.stem('jumps')

'jump'

In [37]:
ps.stem('lovely')

'love'

In [38]:
ps.stem('loving')

'love'

In [40]:
# Snowball Stemmer
ss = SnowballStemmer('english')

In [45]:
ss.stem('curly')

'cur'

In [42]:
ss.stem('run')

'run'

In [48]:
## Lemmatization
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
def get_wordnet_pos(word):
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ, "N": wordnet.NOUN, "V": wordnet.VERB, "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

wn = WordNetLemmatizer()
word = 'curly'
# wn.lemmatize('jumping')
wn.lemmatize(word, get_wordnet_pos(word))

'curly'

### Building a Vocab & Vectorization

In [61]:
# Sample Corpus - Contains 4 Documents, each document can have 1 or more sentences
corpus = [
        'Indian cricket team will wins World Cup, says Capt. Virat Kohli. World cup will be held at Sri Lanka.',
        'We will win next Lok Sabha Elections, says confident Indian PM',
        'The nobel laurate won the hearts of the people.',
        'The movie Raazi is an exciting Indian Spy thriller based upon a real story.'
]

In [62]:
from sklearn.feature_extraction.text import CountVectorizer

In [63]:
cv = CountVectorizer()

In [64]:
vectorized_corpus = cv.fit_transform(corpus)

In [65]:
vectorized_corpus = vectorized_corpus.toarray()

In [66]:
vectorized_corpus
# len(vectorized_corpus[0])
# print(vectorized_corpus[0])

array([[0, 1, 0, 1, 1, 0, 1, 2, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 2, 0, 1, 0, 2],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [67]:
print(cv.vocabulary_)

{'indian': 12, 'cricket': 6, 'team': 31, 'will': 37, 'wins': 39, 'world': 41, 'cup': 7, 'says': 27, 'capt': 4, 'virat': 35, 'kohli': 14, 'be': 3, 'held': 11, 'at': 1, 'sri': 29, 'lanka': 15, 'we': 36, 'win': 38, 'next': 19, 'lok': 17, 'sabha': 26, 'elections': 8, 'confident': 5, 'pm': 23, 'the': 32, 'nobel': 20, 'laurate': 16, 'won': 40, 'hearts': 10, 'of': 21, 'people': 22, 'movie': 18, 'raazi': 24, 'is': 13, 'an': 0, 'exciting': 9, 'spy': 28, 'thriller': 33, 'based': 2, 'upon': 34, 'real': 25, 'story': 30}


In [68]:
len(cv.vocabulary_.keys())

42

In [69]:
# Reverse Mapping!
numbers = vectorized_corpus[2]
numbers

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 1, 0],
      dtype=int64)

In [70]:
s = cv.inverse_transform([numbers])
print(s)

[array(['hearts', 'laurate', 'nobel', 'of', 'people', 'the', 'won'],
      dtype='<U9')]


#### Vectorization with  Stopword Removal

In [82]:
def myTokenizer(document):
    words = tokenizer.tokenize(document.lower())
    # Remove Stopwords
    words = remove_stopwords(words,sw)
    return words
    
    

In [83]:
#myTokenizer(sentence)
#print(sentence)

In [84]:
cv = CountVectorizer(tokenizer=myTokenizer)

In [85]:
vectorized_corpus = cv.fit_transform(corpus).toarray()

In [86]:
print(vectorized_corpus)

[[0 1 0 1 2 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 2]
 [0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0]]


In [87]:
print(len(vectorized_corpus[0]))

33


In [88]:
cv.inverse_transform(vectorized_corpus)

[array(['capt.', 'cricket', 'cup', 'held', 'indian', 'kohli.', 'lanka.',
        'says', 'sri', 'team', 'virat', 'wins', 'world'], dtype='<U9'),
 array(['confident', 'elections', 'indian', 'lok', 'next', 'pm', 'sabha',
        'says', 'win'], dtype='<U9'),
 array(['hearts', 'laurate', 'nobel', 'people.'], dtype='<U9'),
 array(['based', 'exciting', 'indian', 'movie', 'raazi', 'real', 'spy',
        'story.', 'thriller', 'upon'], dtype='<U9')]

In [66]:
# For Test Data
test_corpus = [
        'Indian cricket rock !',        
]


In [67]:
cv.transform(test_corpus).toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### More ways to Create Features
- Unigram - every word as a feature
- Bigrams
- Trigrams
- n-grams 
- TF-IDF Normalisation

In [89]:
sent_1  = ["this is good movie"]
sent_2 = ["this is good movie but actor is not present"]
sent_3 = ["this is not good movie"]


In [97]:
cv = CountVectorizer(ngram_range=(1,3))

In [98]:
docs = [sent_1[0],sent_2[0]]
cv.fit_transform(docs)

<2x23 sparse matrix of type '<class 'numpy.int64'>'
	with 32 stored elements in Compressed Sparse Row format>

In [99]:
cv.vocabulary_

{'this': 20,
 'is': 9,
 'good': 6,
 'movie': 14,
 'this is': 21,
 'is good': 10,
 'good movie': 7,
 'this is good': 22,
 'is good movie': 11,
 'but': 3,
 'actor': 0,
 'not': 17,
 'present': 19,
 'movie but': 15,
 'but actor': 4,
 'actor is': 1,
 'is not': 12,
 'not present': 18,
 'good movie but': 8,
 'movie but actor': 16,
 'but actor is': 5,
 'actor is not': 2,
 'is not present': 13}

## Tf-idf Normalisation

- Avoid features that occur very often, becauase they contain less information
- Information decreases as the number of occurences increases across different type of documents
- So we define another term - term-document-frequency which associates a weight with every term

In [100]:
sent_1  = "this is good movie"
sent_2 = "this was good movie"
sent_3 = "this is not good movie"

corpus = [sent_1,sent_2,sent_3]

In [101]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [102]:
tfidf = TfidfVectorizer()



In [103]:
vc = tfidf.fit_transform(corpus).toarray()

In [104]:
print(vc)

[[0.46333427 0.59662724 0.46333427 0.         0.46333427 0.        ]
 [0.41285857 0.         0.41285857 0.         0.41285857 0.69903033]
 [0.3645444  0.46941728 0.3645444  0.61722732 0.3645444  0.        ]]


In [105]:
tfidf.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'was': 5, 'not': 3}