In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('./data1.csv',header = None)
labels = pd.read_csv('./label1.csv',header = None)

In [3]:
data

0         1         2         3         4         5         6   \
0     -0.446891 -0.013397  0.232645  2.156649  1.652923 -0.210531 -0.662227   
1      0.243747 -1.144175 -0.622214 -0.661979 -0.373315  0.520313 -1.307954   
2     -1.417799 -0.088833 -0.647181 -1.141497 -1.321100  0.686798 -1.045569   
3      0.656784  0.381201 -1.039011  1.285315  0.808324  1.428519 -1.144367   
4      1.098520  1.706769 -1.030370  2.001009  2.751551  1.202229 -0.941066   
...         ...       ...       ...       ...       ...       ...       ...   
19995  0.146324 -0.618555  0.547413  0.851301  0.838880 -1.248402  0.698199   
19996 -2.227923 -0.327196  1.258849 -0.945254  3.925262  0.316686 -1.061159   
19997 -0.800405  1.477997  0.090057 -0.973997 -0.204970  0.224539  0.302265   
19998 -1.217344 -0.785401 -0.413781 -0.335324  0.181671 -1.685733 -0.437981   
19999  1.601005 -0.890398 -1.425049  0.887501  0.167205 -0.395042 -0.512554   

             7         8         9         10        11        12        13  \
0      0.705144  1.434684 -0.445750 -0.178501 -0.905503 -0.594099 -0.728586   
1      1.639481 -2.838816  0.331636  0.100261 -1.173067 -0.079774  2.194899   
2     -0.376153 -2.272447 -0.669733 -1.070732  1.091993  0.692293  0.937617   
3     -0.609958  0.983676  0.060917  0.471647 -0.594279  2.104027 -1.113597   
4      1.965282  2.979131  1.402483 -1.432987  0.400322 -0.839851 -1.580974   
...         ...       ...       ...       ...       ...       ...       ...   
19995 -0.545033  0.994348 -0.054620  0.581239 -1.842074 -0.552879 -0.102096   
19996  1.846706  3.692157  0.698035 -0.184239 -0.546036 -0.457919 -1.030581   
19997  0.361146 -1.906636  1.381875  0.034366  1.690199 -0.901569  2.183842   
19998 -1.176626 -1.434436 -0.880986  2.117703 -2.136842 -1.185261  1.547704   
19999  0.050777 -0.034945 -0.289219  0.639189  0.981751 -0.110296 -0.187214   

             14        15        16        17        18        19  
0     -0.627002 -0.240520  0.131696 -0.945878  1.840922 -0.279024  
1      0.242839  0.412164 -0.328714  0.902931 -1.418728 -0.290139  
2      0.262142  0.399238  0.614614  1.209465 -1.526386  0.337771  
3     -0.188799  1.226253 -1.067763 -0.350275 -0.746426 -1.258696  
4     -0.659587  2.292688  0.494188 -1.583187 -2.468254 -0.469648  
...         ...       ...       ...       ...       ...       ...  
19995  0.307538 -1.267832 -0.165875 -0.717397 -0.808588  0.796346  
19996  2.406014 -0.978943 -0.086879 -1.964453 -0.875574  1.535930  
19997  0.831008  0.036308  0.516088  0.378670  0.110968 -0.176363  
19998  1.174712 -0.429117  0.132068  0.249277 -0.941496  1.661661  
19999 -0.226811 -0.547772 -0.006706 -0.023773  1.220809  1.489330  

[20000 rows x 20 columns]

In [4]:
labels

0
0      3
1      2
2      2
3      3
4      3
...   ..
19995  3
19996  1
19997  2
19998  2
19999  0

[20000 rows x 1 columns]

In [5]:
npData = data.values
npLabels = labels.values

In [6]:
print(np.max(npLabels))
print(np.max(npData))

4
6.873800762086958


In [7]:
np.unique(npLabels)

array([0, 1, 2, 3, 4])

In [8]:
num = np.max(npLabels)+1
oneHot = np.eye(num)[npLabels]
print(oneHot.ndim)
print(oneHot.shape)

3
(20000, 1, 5)


In [9]:
oneHotRe = np.reshape(oneHot,[20000,5])
print(oneHotRe)

[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [10]:
trainData, testData, trainLabel, testLabel = train_test_split(npData,oneHotRe,train_size=0.8)

In [11]:
print(trainData.shape,testData.shape,trainLabel.shape,testLabel.shape)

(16000, 20) (4000, 20) (16000, 5) (4000, 5)


In [45]:
class MLP:
    def __init__(self,InputL,hiddenLayers,OutputL):

        self.weights = []
        self.bias = []

        self.weights.append(np.random.normal(0,1/np.sqrt(InputL),size=(InputL,hiddenLayers[0])))
        self.bias.append(np.zeros((hiddenLayers[0],)))

        for i in range(1,len(hiddenLayers)):
            self.weights.append(np.random.normal(0,1/np.sqrt(hiddenLayers[i-1]),size=(hiddenLayers[i-1],hiddenLayers[i])))
            self.bias.append(np.zeros((hiddenLayers[i],)))

        self.weights.append(np.random.normal(0,1/np.sqrt(hiddenLayers[-1]),size=(hiddenLayers[-1],OutputL)))
        self.bias.append(np.zeros((OutputL,)))

    def sigmoidActivation(self,Z):
        return 1.0/(1.0+np.exp(-Z))

    def softmaxActivation(self,Z):
        temp = np.exp(Z)
        return temp/np.sum(temp,axis = 1,keepdims=True)

    def fit(self,X,y,lr = 0.01,epochs = 1000):
        self.backward(X,y,lr,epochs)

    def predict(self,X):
        ypred = self.forward(X)
        ypred[ypred >= 0.5] = 1.0
        ypred[ypred < 0.5] = 0.0
        return ypred

    def Acc(self,y,t,size):
        maxData = np.argmax(y,axis = 1)
        maxLabel = np.argmax(t,axis = 1)
        compare = np.equal(maxData,maxLabel)
    
        count = np.sum(compare)
        return (count/size)*100

    def costFn(self,y,t):
        return -(t*np.log(y))
        
    def forward(self,X):
        
        a = X
        self.output = [a]
        for i in range(len(self.weights)-1):
            z = a@self.weights[i] + self.bias[i]
            a = self.sigmoidActivation(z)
            self.output.append(a)

        z = a@self.weights[-1] + self.bias[-1]
        a = self.softmaxActivation(z)
        self.output.append(a)
            
        return a

    def derA(self,Z):
        return Z*(1-Z)

    def backward(self,X,y,lr = 0.01,epochs = 100):
        losses = []
        for e in range(epochs):
            ypred = self.forward(X)
    
            delta = [ypred - y]
            gradw = [self.output[-2].T@delta[-1]]

            # print(delta)

            for i in range(len(self.weights)-1,0,-1):
                delta.append((delta[-1]@self.weights[i].T)*self.derA(self.output[i]))
                gradw.append(self.output[i-1].T@delta[-1])


            wn = len(self.weights)-1
            
            for i in range(len(gradw)):
                self.weights[wn] = self.weights[wn] - lr*gradw[i]
                self.bias[wn] = self.bias[wn] - lr*np.sum(delta[i],axis = 0)
                wn -= 1

            loss = np.sum(self.costFn(ypred,y))/ypred.shape[0]
            print("Epoch:",e,"Train Loss:",loss,"Train Accuracy:",self.Acc(ypred,y,y.shape[0]))
            losses.append(loss)

In [46]:
clf = MLP(trainData.shape[1],[40,30,60],trainLabel.shape[1])

In [47]:
clf.fit(trainData,trainLabel,lr=0.0001,epochs = 1000)

Epoch: 0 Train Loss: 1.7749964934650264 Train Accuracy: 20.0125
Epoch: 1 Train Loss: 2.866441252789367 Train Accuracy: 19.9375
Epoch: 2 Train Loss: 3.836362691972623 Train Accuracy: 20.056250000000002
Epoch: 3 Train Loss: 3.378029972718107 Train Accuracy: 20.0125
Epoch: 4 Train Loss: 2.499748115708209 Train Accuracy: 19.8125
Epoch: 5 Train Loss: 1.993142177828308 Train Accuracy: 20.056250000000002
Epoch: 6 Train Loss: 1.6936890081390217 Train Accuracy: 19.8125
Epoch: 7 Train Loss: 1.6171127852127325 Train Accuracy: 20.150000000000002
Epoch: 8 Train Loss: 1.6073767478277854 Train Accuracy: 32.25
Epoch: 9 Train Loss: 1.6066784956439073 Train Accuracy: 32.7
Epoch: 10 Train Loss: 1.6062573987845896 Train Accuracy: 33.34375
Epoch: 11 Train Loss: 1.605826633868904 Train Accuracy: 34.01875
Epoch: 12 Train Loss: 1.605380955225145 Train Accuracy: 34.387499999999996
Epoch: 13 Train Loss: 1.6049180306848039 Train Accuracy: 34.681250000000006
Epoch: 14 Train Loss: 1.6044353578149146 Train Accuracy

In [48]:
clf.predict(testData)

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
def Acc(y,t,size):
    maxData = np.argmax(y,axis = 1)
    maxLabel = np.argmax(t,axis = 1)
    compare = np.equal(maxData,maxLabel)

    count = np.sum(compare)
    return (count/size)*100

In [50]:
Acc(testLabel,clf.predict(testData),testLabel.shape[0])

np.float64(89.425)